### ISSUE TITLE
Error  " ModuleNotFoundError: No module named 'scene_graph_learning' "

### ISSUE THREAD

**Issue by MuMuJun97** [MIT-SPARK/llm_scene_understanding#1]
Hi, @verityw , thanks for your great work!

When I run your source code, I got the following error:
```python
dataset = Matterport3dDataset(
        "./mp_data/" + label_set + "_matterport3d_w_edge.pkl"
    )  # TODO: Change back out of _502030 if needed
...
        with open(dataset_file_path, 'rb') as input_file:
            input_data = pickle.load(input_file)
...

Error: 
Traceback (most recent call last):
     input_data = pickle.load(input_file)
ModuleNotFoundError: No module named 'scene_graph_learning'
```

Maybe the published code doesn't contain complete modules?

Also, I want to know how the `mp_data/nyuClass_matterport3d_w_edge.pkl` file is generated.

Hope to hear from you!
Thanks.

**Comment by verityw** [comment]
Hi,

Yes sorry, the module is missing. I unfortunately cannot release it at the moment, as it's part of an unfinished project -- I will see about just releasing the code needed to load these files.

Said pkl file would also be generated by that module. The basic idea is that it goes through the matterport3d dataset (consisting of building, room, and contained object locations) and constructs a scene graph data structure out of it. There are some additional details in the appendix of https://arxiv.org/abs/2209.05629 for what objects and locations are removed, etc.

**Comment by MuMuJun97** [comment]
Thanks!
Looking forward to the released code.
